package com.leasetrack.service;

import com.leasetrack.dto.response.AuditEventResponse;
import com.leasetrack.dto.response.DeliveryEvidenceResponse;
import com.leasetrack.dto.response.EvidenceDocumentResponse;
import com.leasetrack.dto.response.EvidencePackageAttemptResponse;
import com.leasetrack.dto.response.EvidencePackageResponse;
import com.leasetrack.dto.response.TrackingEventResponse;
import com.leasetrack.exception.EvidencePackageGenerationException;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

@Service
public class EvidencePackagePdfService {

    private static final float MARGIN = 50;
    private static final float LINE_HEIGHT = 14;
    private static final int BODY_WRAP_CHARS = 95;
    private static final DateTimeFormatter INSTANT_FORMATTER = DateTimeFormatter.ISO_INSTANT;
    private static final PDType1Font FONT = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
    private static final PDType1Font BOLD_FONT = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

    public byte[] render(EvidencePackageResponse evidencePackage) {
        try (PDDocument document = new PDDocument();
                ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(document);
            writer.heading("Lease-Track Evidence Package", 18);
            writer.line("Package ID: " + evidencePackage.packageId());
            writer.line("Package version: " + evidencePackage.packageVersion());
            writer.line("Package hash: " + evidencePackage.packageHash());
            writer.line("Generated at: " + format(evidencePackage.generatedAt()));
            writer.line("Generated by user: " + evidencePackage.generatedByUserId());
            writer.blank();

            writer.heading("Notice", 14);
            writer.line("Notice ID: " + evidencePackage.noticeId());
            writer.line("Recipient: " + value(evidencePackage.notice().recipientName()));
            writer.line("Recipient contact: " + value(evidencePackage.notice().recipientContactInfo()));
            writer.line("Notice type: " + evidencePackage.notice().noticeType());
            writer.line("Status: " + evidencePackage.notice().status());
            writer.line("Strongest evidence: " + evidencePackage.strongestEvidenceStrength());
            writer.line("Created at: " + format(evidencePackage.notice().createdAt()));
            writer.line("Updated at: " + format(evidencePackage.notice().updatedAt()));
            writer.line("Closed at: " + format(evidencePackage.notice().closedAt()));
            writer.blank();

            writer.heading("Delivery Attempts", 14);
            if (evidencePackage.attempts().isEmpty()) {
                writer.line("No delivery attempts recorded.");
            }
            for (EvidencePackageAttemptResponse attemptPackage : evidencePackage.attempts()) {
                var attempt = attemptPackage.attempt();
                writer.subheading("Attempt " + attempt.attemptNumber() + " - " + attempt.deliveryMethod());
                writer.line("Attempt ID: " + attempt.id());
                writer.line("Status: " + attempt.status());
                writer.line("Deadline: " + format(attempt.deadlineAt()));
                writer.line("Sent at: " + format(attempt.sentAt()));
                writer.line("Delivered at: " + format(attempt.deliveredAt()));
                writer.line("Tracking sync: " + attempt.trackingSyncStatus());
                writer.line("Last tracking check: " + format(attempt.lastTrackingCheckedAt()));
                writeEvidence(writer, attemptPackage.evidence());
                writeDocuments(writer, attemptPackage.evidenceDocuments());
                writeTrackingHistory(writer, attemptPackage.trackingHistory());
                writer.blank();
            }

            writer.heading("Audit Log", 14);
            if (evidencePackage.auditEvents().isEmpty()) {
                writer.line("No audit events recorded.");
            }
            for (AuditEventResponse auditEvent : evidencePackage.auditEvents()) {
                writer.line(format(auditEvent.createdAt())
                        + " | " + auditEvent.eventType()
                        + " | " + value(auditEvent.actorReference())
                        + " | " + value(auditEvent.details()));
            }

            writer.close();
            document.save(output);
            return output.toByteArray();
        } catch (IOException ex) {
            throw new EvidencePackageGenerationException("Unable to render evidence package PDF", ex);
        }
    }

    private void writeEvidence(PdfWriter writer, DeliveryEvidenceResponse evidence) throws IOException {
        writer.subheading("Evidence");
        if (evidence == null) {
            writer.line("No proof-of-delivery evidence recorded.");
            return;
        }
        writer.line("Evidence ID: " + evidence.id());
        writer.line("Carrier: " + value(evidence.carrierName()) + " (" + value(evidence.carrierCode()) + ")");
        writer.line("Tracking number: " + value(evidence.trackingNumber()));
        writer.line("Carrier receipt: " + value(evidence.carrierReceiptRef()));
        writer.line("Delivery confirmation: " + value(evidence.deliveryConfirmation()));
        writer.line("Latest status: " + value(evidence.latestTrackingStatus()));
        writer.line("Latest status code: " + value(evidence.latestTrackingStatusCode()));
        writer.line("Latest tracking event: " + format(evidence.latestTrackingEventAt()));
        writer.line("Provider error: " + value(evidence.latestTrackingProviderError()));
        writer.line("Evidence strength: " + evidence.evidenceStrength());
    }

    private void writeDocuments(PdfWriter writer, List<EvidenceDocumentResponse> documents) throws IOException {
        writer.subheading("Evidence Documents");
        if (documents.isEmpty()) {
            writer.line("No evidence documents uploaded.");
            return;
        }
        for (EvidenceDocumentResponse document : documents) {
            writer.line(document.documentType()
                    + " | " + value(document.originalFilename())
                    + " | " + document.sizeBytes() + " bytes"
                    + " | " + document.storageProvider() + ":" + document.storageKey()
                    + " | sha256=" + document.sha256Checksum());
        }
    }

    private void writeTrackingHistory(PdfWriter writer, List<TrackingEventResponse> trackingHistory) throws IOException {
        writer.subheading("Tracking History");
        if (trackingHistory.isEmpty()) {
            writer.line("No tracking history recorded.");
            return;
        }
        for (TrackingEventResponse event : trackingHistory) {
            writer.line(format(event.eventAt())
                    + " | " + value(event.status())
                    + " | code=" + value(event.statusCode())
                    + " | delivered=" + event.delivered()
                    + " | key=" + value(event.eventKey()));
        }
    }

    private static String format(java.time.Instant instant) {
        return instant == null ? "not recorded" : INSTANT_FORMATTER.format(instant);
    }

    private static String value(Object value) {
        if (value == null) {
            return "not recorded";
        }
        String text = Objects.toString(value);
        return StringUtils.hasText(text) ? text : "not recorded";
    }

    private static final class PdfWriter {

        private final PDDocument document;
        private PDPageContentStream contentStream;
        private float y;

        private PdfWriter(PDDocument document) throws IOException {
            this.document = document;
            addPage();
        }

        private void heading(String text, int fontSize) throws IOException {
            ensureSpace(LINE_HEIGHT * 2);
            write(text, BOLD_FONT, fontSize);
        }

        private void subheading(String text) throws IOException {
            ensureSpace(LINE_HEIGHT * 2);
            write(text, BOLD_FONT, 11);
        }

        private void line(String text) throws IOException {
            for (String wrappedLine : wrap(safeText(text), BODY_WRAP_CHARS)) {
                write(wrappedLine, FONT, 10);
            }
        }

        private void blank() throws IOException {
            ensureSpace(LINE_HEIGHT);
            y -= LINE_HEIGHT / 2;
        }

        private void close() throws IOException {
            if (contentStream != null) {
                contentStream.close();
            }
        }

        private void write(String text, PDType1Font font, int fontSize) throws IOException {
            ensureSpace(LINE_HEIGHT);
            contentStream.beginText();
            contentStream.setFont(font, fontSize);
            contentStream.newLineAtOffset(MARGIN, y);
            contentStream.showText(text);
            contentStream.endText();
            y -= LINE_HEIGHT;
        }

        private void ensureSpace(float requiredSpace) throws IOException {
            if (y - requiredSpace < MARGIN) {
                addPage();
            }
        }

        private void addPage() throws IOException {
            if (contentStream != null) {
                contentStream.close();
            }
            PDPage page = new PDPage(PDRectangle.LETTER);
            document.addPage(page);
            contentStream = new PDPageContentStream(document, page);
            y = page.getMediaBox().getHeight() - MARGIN;
        }

        private List<String> wrap(String text, int maxChars) {
            List<String> lines = new ArrayList<>();
            String remaining = text;
            while (remaining.length() > maxChars) {
                int splitAt = remaining.lastIndexOf(' ', maxChars);
                if (splitAt <= 0) {
                    splitAt = maxChars;
                }
                lines.add(remaining.substring(0, splitAt).trim());
                remaining = remaining.substring(splitAt).trim();
            }
            lines.add(remaining);
            return lines;
        }

        private String safeText(String text) {
            return text == null
                    ? ""
                    : text.replaceAll("\\p{Cntrl}", " ")
                            .replaceAll("[^\\p{Print}]", "?");
        }
    }
}
